"""add place details and api usage

Revision ID: 70ee4f4eab01
Revises: d90570fcb527
Create Date: 2026-09-27 01:44:02.384537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ee4f4eab01'
down_revision: Union[str, Sequence[str], None] = 'd90570fcb527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api', sa.String(length=50), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api', 'day', name='uq_api_usage_api_day')
    )
    op.add_column('activities', sa.Column('place_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('activities', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_foreign_key('fk_activities_place_id_extracted_places', 'activities', 'extracted_places', ['place_id'], ['id'], ondelete='SET NULL')
    op.add_column('extracted_places', sa.Column('hours_from_post', sa.String(length=255), nullable=True))
    op.add_column('extracted_places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('extracted_places', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('extracted_places', sa.Column('opening_hours', sa.JSON(), nullable=True))
    op.add_column('extracted_places', sa.Column('website', sa.String(length=2048), nullable=True))
    op.add_column('extracted_places', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('extracted_places', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column('extracted_places', sa.Column('details_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('extracted_places', sa.Column('needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('extracted_places', sa.Column('user_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('extracted_places', sa.Column('details_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # Places saved before lookups existed will never be looked up, so let users fill them in
    op.execute("UPDATE extracted_places SET details_status = 'skipped'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_places', 'details_fetched_at')
    op.drop_column('extracted_places', 'user_edited')
    op.drop_column('extracted_places', 'needs_review')
    op.drop_column('extracted_places', 'details_status')
    op.drop_column('extracted_places', 'google_place_id')
    op.drop_column('extracted_places', 'phone')
    op.drop_column('extracted_places', 'website')
    op.drop_column('extracted_places', 'opening_hours')
    op.drop_column('extracted_places', 'longitude')
    op.drop_column('extracted_places', 'latitude')
    op.drop_column('extracted_places', 'hours_from_post')
    op.drop_constraint('fk_activities_place_id_extracted_places', 'activities', type_='foreignkey')
    op.drop_column('activities', 'longitude')
    op.drop_column('activities', 'latitude')
    op.drop_column('activities', 'place_id')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
