"""add place details source

Revision ID: 78b1fed476be
Revises: 70ee4f4eab01
Create Date: 2026-09-27 05:01:29.407624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b1fed476be'
down_revision: Union[str, Sequence[str], None] = '70ee4f4eab01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_places', sa.Column('details_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    # Only OpenStreetMap lookups have run so far
    op.execute("UPDATE extracted_places SET details_source = 'osm' WHERE details_status = 'found'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extracted_places', 'details_source')
    # ### end Alembic commands ###
