"""fix user created_at type

Revision ID: c93560ccb345
Revises: 6f0fba97b322
Create Date: 2026-08-15 19:32:51.932789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c93560ccb345'
down_revision: Union[str, Sequence[str], None] = '6f0fba97b322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN created_at TYPE TIMESTAMPTZ
        USING (
            CURRENT_DATE + created_at
        )
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE users
    ALTER COLUMN created_at TYPE TIMETZ
    USING created_at::TIMETZ
""")
    # ### end Alembic commands ###
